### ISSUE TITLE
Similar project: THREE.Highres (old)

### ISSUE THREAD

**Issue by taseenb** [greggman/dekapng#2]
Sorry I did not know how to share this so I opened an issue, but this is not an issue :)

Just FYI I had worked on a simpler but similar thing a few years ago: THREE.Highres

Repository: https://github.com/taseenb/THREE.Highres
Demo: https://taseenb.github.io/THREE.Highres/demo/index.html

**Comment by greggman** [comment]
great minds think alike 😛

dekapng has been here since 2018 and it's not tied to three.js

https://github.com/greggman/dekapng/commits?author=greggman

**Comment by greggman** [comment]
added a link to your library in the readme since it's probably a quicker solution for three.js users.

https://github.com/greggman/dekapng/commit/147f8918a91a0562c88aba90496aed81b9110c5e
